# Generated by Django 2.2 on 2020-01-05 17:47

import apps.annotate.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeypointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('keypoints_name', djongo.models.fields.ArrayModelField(model_container=django.db.models.fields.TextField)),
                ('keypoints_style', djongo.models.fields.ArrayModelField(blank=True, model_container=django.db.models.fields.TextField)),
                ('joints_index', djongo.models.fields.EmbeddedModelField(blank=True, model_container=apps.annotate.models.JointContainer, model_form_class=apps.annotate.models.JointContainerForm, null=True)),
                ('features', djongo.models.fields.EmbeddedModelField(blank=True, model_container=apps.annotate.models.FeatureContainer, model_form_class=apps.annotate.models.FeatureContainerForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_holder', models.TextField(blank=True)),
                ('license', models.TextField(blank=True)),
                ('copyright', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('filename', models.TextField()),
                ('total_frames', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('channel_no', models.PositiveIntegerField()),
                ('license_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.License')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('filename', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('channel_no', models.PositiveIntegerField()),
                ('license_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.License')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('supercategory', models.TextField(blank=True)),
                ('templates', djongo.models.fields.EmbeddedModelField(blank=True, model_container=apps.annotate.models.Template, model_form_class=apps.annotate.models.TemplateForm, null=True)),
                ('keypointmodel_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.KeypointModel')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveIntegerField(blank=True)),
                ('keypoints_container', djongo.models.fields.EmbeddedModelField(model_container=apps.annotate.models.KeypointContainer, model_form_class=apps.annotate.models.KeypointContainerForm, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Category')),
                ('image_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.Image')),
                ('video_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.Video')),
            ],
        ),
    ]
